[project]
name = "pixi-cuda-environment"
version = "0.1.0"
description = "Add a short description here"
authors = ["Eric Ma <ericmajinglong@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
python = ">=3.10"
jax = "*"
jaxlib = "*"
cuda-version = ">=12.5"
cuda-libraries = "*"
cudnn = "*"
cuda-nvcc = "*"
pytorch = "*"
torchvision = "*"
