[project]
name = "pixi-cuda-environment"
version = "0.1.0"
description = "Add a short description here"
authors = ["Eric Ma <ericmajinglong@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
python = ">=3.10"
cuda-version = "==12.1"
cuda-libraries = "*"
cudnn = "*"
pytorch = "*"
torchvision = "*"
ipython = ">=8.26.0,<9"
jax = "*"
jaxlib = "* *cuda*"

[system-requirements]
cuda = "12.0"
