name: Run software tests

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        environment: [ default, cuda ]
    name: Run tests

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - uses: prefix-dev/setup-pixi@v0.8.1
      with:
        pixi-version: v0.25.0
        cache: true

    - run: pixi run -e ${{ matrix.environment}} test
